# Generated by Django 5.1.15 on 2026-09-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.CharField(db_index=True, help_text='OPIS Truckstop ID', max_length=64)),
                ('name', models.CharField(help_text='Truckstop / Station Name', max_length=255)),
                ('address', models.CharField(help_text='Street / Highway Exit Address', max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=10)),
                ('rack_id', models.CharField(blank=True, default='', help_text='Rack ID', max_length=50)),
                ('retail_price', models.DecimalField(db_index=True, decimal_places=4, help_text='Retail fuel price per gallon (USD)', max_digits=7)),
                ('latitude', models.FloatField(db_index=True, help_text='Latitude in decimal degrees')),
                ('longitude', models.FloatField(db_index=True, help_text='Longitude in decimal degrees')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'fuel_stations',
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['latitude', 'longitude'], name='station_lat_lon_idx'), models.Index(fields=['state', 'city'], name='station_state_city_idx'), models.Index(fields=['opis_id'], name='station_opis_idx')],
            },
        ),
    ]
